name: Scrape Twitch

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run the Python script
      run: |
        python src/assets/misc/scraptwitch.py

    - name: Display JSON content
      run: |
        cat src/assets/misc/twitch_channels.json

    - name: Force add and commit changes
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add -f src/assets/misc/twitch_channels.json
        git commit -m "Update twitch_channels.json from GitHub Actions" || echo "No changes to commit"
        git push origin main
