name: Scrape YouTube Channels

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run the Python script
      run: |
        python src/assets/misc/scrapyb.py

    - name: Display JSON content
      run: |
        cat src/assets/misc/channels_info.json

    - name: Check permissions of directory
      run: |
        ls -la src/assets/misc && pwd

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add src/assets/misc/channels_info.json
        git commit -m "Update channels_info.json from GitHub Actions" || echo "No changes to commit"
        git push origin main
