name: Scrape YouTube Channels

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Download the Python script
      run: |
        curl -O https://raw.githubusercontent.com/Frozenka/hacking-france/main/src/assets/misc/scrapyb.py

    - name: Run the Python script
      run: |
        python src/assets/misc/scrapyb.py

    - name: Upload JSON result
      uses: actions/upload-artifact@v3
      with:
        name: channels-info
        path: src/assets/misc/channels_info.json
